{
 "title": "Ceph RGW Usage",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(rgw_total_ops, cluster)"
    }
   },
   { "name": "rate_interval", "label": "rate_interval", "query": "5m,10m,30m,1h,6h" }
  ]
 },
 "panels": [
  {
   "title": "bits/s Received",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(8*rate(rgw_total_bytes_received{cluster=~\"$cluster\"}[$rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "bits/s Sent",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(8*rate(rgw_total_bytes_sent{cluster=~\"$cluster\"}[$rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "bits/s Received per User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "topk(5,sum(8*rate(rgw_total_bytes_received{cluster=~\"$cluster\"}[$rate_interval])) by (user))",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "bits/s Sent per User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "topk(5,sum(8*rate(rgw_total_bytes_sent{cluster=~\"$cluster\"}[$rate_interval])) by (user))",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Ops Total",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rgw_total_ops{cluster=~\"$cluster\"}[$rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "S3 Probes Success",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\",job=\"s3-prober\", operation=~\"get|put|remove|stat\"}",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Ops per User",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5,sum(rate(rgw_total_ops{cluster=~\"$cluster\"}[$rate_interval])) by (user))",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "S3 Probes Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(probe_duration_seconds{cluster=~\"$cluster\",job=\"s3-prober\", operation=~\"get|put|remove|stat\"}[$rate_interval])) by (operation)",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Latency PUT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(ceph_rgw_put_initial_lat_sum{cluster=~\"$cluster\"}[$rate_interval]) / rate(ceph_rgw_put_initial_lat_count{cluster=~\"$cluster\"}[$rate_interval]))",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Latency GET",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(ceph_rgw_get_initial_lat_sum{cluster=~\"$cluster\"}[$rate_interval]) / rate(ceph_rgw_get_initial_lat_count{cluster=~\"$cluster\"}[$rate_interval]))",
     "legendFormat": "get"
    }
   ]
  }
 ]
}