apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: rgw-exporter
spec:
  endpoints:
    - path: /metrics
      port: metrics
      interval: 60s
      scrapeTimeout: 30s
  selector:
    matchLabels:
      app: rgw-exporter
