apiVersion: v1
kind: Service
metadata:
  name: rgw-exporter
  labels:
    app: rgw-exporter
spec:
  ports:
    - name: metrics
      port: 9080
      targetPort: metrics
  selector:
    app: rgw-exporter
